# Generated by Django 4.2.16 on 2026-06-23 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("tenants", "0001_initial"),
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Quantidade"
                    ),
                ),
                ("status", models.CharField(max_length=50, verbose_name="Status")),
                (
                    "production_type",
                    models.CharField(max_length=50, verbose_name="Tipo de Produção"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Iniciado em"
                    ),
                ),
                (
                    "expected_finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Previsão de término"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Finalizado em"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_orders",
                        to="catalog.product",
                        verbose_name="Product",
                    ),
                ),
                (
                    "product_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_orders",
                        to="catalog.productvariant",
                        verbose_name="Product Variant",
                    ),
                ),
                (
                    "responsible_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="production_orders",
                        to="users.user",
                        verbose_name="Responsible User",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_orders",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ordem de Produção",
                "verbose_name_plural": "Ordens de Produção",
            },
        ),
        migrations.CreateModel(
            name="ProductionStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nome do Estágio"),
                ),
                (
                    "stage_order",
                    models.PositiveIntegerField(verbose_name="Ordem do Estágio"),
                ),
                ("status", models.CharField(max_length=50, verbose_name="Status")),
                (
                    "expected_finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Previsão de término"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Finalizado em"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "production_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="production.productionorder",
                        verbose_name="Ordem de Produção",
                    ),
                ),
                (
                    "responsible_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="production_stages",
                        to="users.user",
                        verbose_name="Responsável",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estágio de Produção",
                "verbose_name_plural": "Estágios de Produção",
                "ordering": ["stage_order"],
            },
        ),
    ]
