# Generated by Django 4.2.16 on 2026-06-23 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cpf",
                    models.CharField(max_length=14, unique=True, verbose_name="CPF"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                ("surname", models.CharField(max_length=255, verbose_name="Sobrenome")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Número de Telefone",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Nascimento"
                    ),
                ),
                ("password", models.CharField(max_length=255, verbose_name="Senha")),
                (
                    "status",
                    models.CharField(
                        default="active", max_length=20, verbose_name="Status"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "master_type",
                    models.CharField(
                        choices=[
                            ("primary", "Master Principal"),
                            ("financial", "Master Financeiro"),
                            ("operational", "Master Operacional"),
                            ("administrative", "Master Administrativo"),
                        ],
                        default="primary",
                        max_length=20,
                        verbose_name="Tipo de Master",
                    ),
                ),
                (
                    "can_manage_billing",
                    models.BooleanField(
                        default=False, verbose_name="Pode Gerenciar Cobrança"
                    ),
                ),
                (
                    "can_manage_users",
                    models.BooleanField(
                        default=False, verbose_name="Pode Gerenciar Usuários"
                    ),
                ),
                (
                    "can_manage_domains",
                    models.BooleanField(
                        default=False, verbose_name="Pode Gerenciar Domínios"
                    ),
                ),
                (
                    "can_manage_contracts",
                    models.BooleanField(
                        default=False, verbose_name="Pode Gerenciar Contratos"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="active", max_length=20, verbose_name="Status"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Usuário Primário"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="masters",
                        to="tenants.tenant",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="master_profile",
                        to="users.user",
                        verbose_name="Usuário",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "permissions",
                    models.JSONField(blank=True, null=True, verbose_name="Permissões"),
                ),
                (
                    "status",
                    models.CharField(
                        default="active", max_length=20, verbose_name="Status"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="tenants.tenant",
                        verbose_name="Empresa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LGPDConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            ("marketing", "Marketing"),
                            ("privacy_policy", "Política de Privacidade"),
                            ("terms_of_use", "Termos de Uso"),
                            ("cookies", "Cookies"),
                            ("data_processing", "Processamento de Dados"),
                        ],
                        default="marketing",
                        max_length=50,
                        verbose_name="Tipo de Consentimento",
                    ),
                ),
                ("accepted", models.BooleanField(default=False, verbose_name="Aceito")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Endereço IP"
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Aceito em"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expira em"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lgpd_consents",
                        to="users.user",
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consentimento LGPD",
                "verbose_name_plural": "Consentimentos LGPD",
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_function",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Função"
                    ),
                ),
                (
                    "salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Salário",
                    ),
                ),
                (
                    "schedule",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Horário de Trabalho",
                    ),
                ),
                (
                    "admission_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Admissão"
                    ),
                ),
                (
                    "termination_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Demissão"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="active", max_length=20, verbose_name="Status"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "corporate_email",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="tenants.corporateemail",
                        verbose_name="Email Corporativo",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="users.role",
                        verbose_name="Cargo",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="tenants.tenant",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_profile",
                        to="users.user",
                        verbose_name="Usuário",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cep", models.CharField(max_length=9, verbose_name="CEP")),
                ("street", models.CharField(max_length=255, verbose_name="Logradouro")),
                ("number", models.CharField(max_length=20, verbose_name="Número")),
                (
                    "complement",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Complemento",
                    ),
                ),
                ("city", models.CharField(max_length=30, verbose_name="Cidade")),
                ("state", models.CharField(max_length=2, verbose_name="Estado")),
                ("district", models.CharField(max_length=255, verbose_name="Bairro")),
                (
                    "address_type",
                    models.CharField(
                        choices=[
                            ("residential", "Residencial"),
                            ("commercial", "Comercial"),
                            ("delivery", "Entrega"),
                            ("billing", "Cobrança"),
                        ],
                        default="residential",
                        max_length=20,
                        verbose_name="Tipo de Endereço",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="active", max_length=20, verbose_name="Status"
                    ),
                ),
                (
                    "is_main",
                    models.BooleanField(
                        default=False, verbose_name="Endereço Principal"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="users.user",
                        verbose_name="Usuário",
                    ),
                ),
            ],
        ),
    ]
