# Generated by Django 4.2.16 on 2026-06-23 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(max_length=100, verbose_name="Número da Fatura"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor"
                    ),
                ),
                ("issued_date", models.DateField(verbose_name="Data de Emissão")),
                ("due_date", models.DateField(verbose_name="Data de Vencimento")),
                (
                    "status",
                    models.CharField(
                        default="pending", max_length=20, verbose_name="Status"
                    ),
                ),
                (
                    "access_key",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Chave de Acesso",
                    ),
                ),
                (
                    "danfe_url",
                    models.URLField(blank=True, null=True, verbose_name="URL da DANFE"),
                ),
                (
                    "xml_url",
                    models.URLField(blank=True, null=True, verbose_name="URL do XML"),
                ),
                (
                    "sefaz_protocol",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Protocolo SEFAZ",
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Motivo de Rejeição"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="orders.order",
                        verbose_name="Pedido",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FiscalInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cnpj", models.CharField(max_length=18, verbose_name="CNPJ")),
                (
                    "state_registration",
                    models.CharField(max_length=20, verbose_name="Inscrição Estadual"),
                ),
                (
                    "municipal_registration",
                    models.CharField(max_length=20, verbose_name="Inscrição Municipal"),
                ),
                (
                    "tax_regime",
                    models.CharField(
                        choices=[
                            ("simples_nacional", "Simples Nacional"),
                            ("lucro_presumido", "Lucro Presumido"),
                            ("lucro_real", "Lucro Real"),
                            (
                                "microempreendedor_individual",
                                "Microempreendedor Individual (MEI)",
                            ),
                        ],
                        default="simples_nacional",
                        max_length=50,
                        verbose_name="Regime Tributário",
                    ),
                ),
                ("cnae", models.CharField(max_length=20, verbose_name="CNAE")),
                (
                    "legal_name",
                    models.CharField(max_length=255, verbose_name="Razão Social"),
                ),
                (
                    "trade_name",
                    models.CharField(max_length=255, verbose_name="Nome Fantasia"),
                ),
                ("status", models.BooleanField(default=True, verbose_name="Status")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiscal_information",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DigitalCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_name",
                    models.CharField(
                        max_length=255, verbose_name="Nome do Certificado"
                    ),
                ),
                (
                    "certificate_file",
                    models.FileField(
                        upload_to="certificates/", verbose_name="Arquivo do Certificado"
                    ),
                ),
                (
                    "certificate_password",
                    models.CharField(
                        max_length=255, verbose_name="Senha do Certificado"
                    ),
                ),
                ("expiration_date", models.DateField(verbose_name="Data de Expiração")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Ativo"),
                            ("expired", "Expirado"),
                            ("revoked", "Revogado"),
                            ("inactive", "Inativo"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="digital_certificate",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
        ),
    ]
